# Generated by Django 3.2.16 on 2023-08-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_registraionno_student_registrationno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('remainingTemplate', models.CharField(blank=True, max_length=150)),
                ('plan', models.CharField(choices=[('gold', 'Gold Plan'), ('silver', 'Silver Plan'), ('platinum', 'Platinum Plan')], max_length=10)),
            ],
        ),
    ]
