# Generated by Django 3.2.16 on 2023-08-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_templatecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecount',
            name='selectedTemplate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templatecount',
            name='remainingTemplate',
            field=models.PositiveIntegerField(),
        ),
    ]
