# Generated by Django 3.2.16 on 2023-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20230821_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatecount',
            old_name='selectedTemplate',
            new_name='maximumTemplate',
        ),
        migrations.AlterField(
            model_name='templatecount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templatecount',
            name='plan',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='templatecount',
            name='remainingTemplate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
