# Generated by Django 4.1.1 on 2023-08-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20230821_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatecount',
            old_name='count',
            new_name='selectedTemplate',
        ),
    ]
