# Generated by Django 4.1.1 on 2023-08-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_count_templatecount_selectedtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatecount',
            old_name='selectedTemplate',
            new_name='count',
        ),
    ]
